apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: aks-api  
spec:  
  replicas: 1 
  selector:
      matchLabels:
        name: aks-api  
  template:  
    metadata:  
      labels:  
        name: aks-api  
    spec:  
      containers:  
      - name: aksdemo-api  
        image: shippingregistry.azurecr.io/aksdemo:dev
        command: ["sleep"]
        args: ["infinity"] 
        ports:  
        - containerPort: 80
        resources:
          limits:
            memory: "200Mi"
          requests:
            memory: "100Mi"
          
      imagePullSecrets:  
      - name: aksdemo-key
      
          
---  
apiVersion: v1  
kind: Service  
metadata:  
  name: aks-api  
spec:  
  type: LoadBalancer  
  ports:  
  - port: 80  
  selector:  
    app: aks-api 